### ISSUE TITLE
Create Public Page on Notion for Member Orgs

### ISSUE THREAD

**Issue by NAMRATA-WOKE** [Green-Software-Foundation/committees#4]
What: A public page about the Communications Committee to guide org leads in identifying the most suitable representative. 
Why: Org leads will likely have to distribute information internally to get buy-in for engagement.

Public Page: https://grnsft.notion.site/Empowering-Your-Voice-Join-the-GSF-Communications-Committee-2068a5a3c429444fa4c8cb28349db12b

**Comment by NAMRATA-WOKE** [comment]
@zanete can you help create a shortlink?

**Comment by zanete** [comment]
@NAMRATA-WOKE sure thing, what would you like it to be? What would make sense? Should there be a comms committee related shortlink folder @jawache ?
